### ISSUE TITLE
User Sign Up Onboarding Page

### ISSUE THREAD

**Issue by chanteriam** [uchicago-capp-30320/ShoulderToShoulder#23]
## Implementation Details
Immediately after a user submits their sign up form, they should be redirected to an onboarding page that allows them to customize their S2S experiences. This page will include the following components:
- [ ] An (optional) demographics survey that collects information about the demographics of the user
- [ ] An event preferences survey (required) that collects the user's favorite hobbies, event locations (zip codes probably), group sizes for events, etc.
- [ ] An event recommendation calibration survey, that presents users with a series of events (maybe 10 max?) and asks them how likely they would be to go to the specified event.

**Comment by chanteriam** [comment]
@ethanarsht @dscolby I've added the specific questions that will be asked; do you think these work for your models?

**Comment by dscolby** [comment]
@chanteriam That looks great to me!

**Comment by chanteriam** [comment]
## Feedback (04/10)
### Demographics
- [ ] Add political affiliation
- [ ] Add spiritual as a religious affiliation
- [ ] Cut down on genders to man, woman, nonbinary

### Schedule/Availability
- [ ] On the availability, add shortcuts for preselecting times - weekend and weekday mornings, evening, afternoons, etc.
- [ ] Time categories: 
    - early morning (5-8am)
    - Morning (9-12a)
    - Afternoon (1-4p)
    - Evening (5p-8p)
    - Night (9-12)
    - Middle of the night (1-4am)
   
### Preferences
- [ ] Alter language of similarity preference to be like “When you hang out with people, how similar do you like them to be to you?”, etc.

### Scenarios
- [ ] For the scenarios, visually separate the events Event 1: and Event 2:
    - Take away leading 0s for the times
    - Change raw continuous numbers to their categories
